### ISSUE TITLE
Dead links / Links clean up

### ISSUE THREAD

**Issue by OpossumPetya** [szabgab/whitecamel.org#16]
There are a lot of dead links in award recipient's individual pages.
- it's useless
- it may be bad for SEO with some search engines, if I'm not mistaken.

My general suggestion is to replace them with links to the Web Archive (Wayback Machine) copies. Or remove anchors to those URLs at all.

What do you think?

**Comment by OpossumPetya** [comment]
I went through the list of awardees in the first column on the index page, and found following issues (I'll continue working through the list):


_* WBM == Wayback Machine, web.archive.org_

**Adam Turoff**
- http://ny.pm.org/ -- is now "database of the names and armory registered by the College of Arms of the Society for Creative Anachronism". Wayback Machine shows (https://web.archive.org/web/20170216111727/http://ny.pm.org/) at some point there was a text saying the site is archived, and encouraged people to use https://www.meetup.com/The-New-York-Perl-Meetup-Group/. Also this is the current link at https://www.pm.org/groups/0.html
Suggestion: replace link to the meetup URL


**Amalia Pomian**
- http://cluj.pm/ -- site no longer exist (since 2021?)
Suggestion: link to the latest WBM record: https://web.archive.org/web/20211202080119/https://cluj.pm/


**Andrew Shitov**
- https://event.perlrussia.ru/fe2008/ -- "Not Found". and perlrussia.ru is gone.
Suggestion: link to the latest WBM record: https://web.archive.org/web/20160515075029/https://event.perlrussia.ru/fe2008/
- http://andy.sh/ - "404 Not Found"; new site appears to be at andrewshitov.com
Suggestion: link to https://andrewshitov.com/


**Ask Bjørn Hansen**
- http://www.valueclick.com/ -- is blocked by ad blocking extension, because the site is in "Ad and tracking server list". Otherwise this site is being redirected to epsilon.com
Suggestion: in text "Special thanks to Ask's employer, ValueClick, for allowing him to help Perl." remove the link from the "ValueClick"


**Breno G. de Oliveira**
- http://yapcbrasil.org.br/2011/ -- yapcbrasil.org.br no longer exist
Suggestion: link to the latest WBM record: https://web.archive.org/web/20150218004509/http://yapcbrasil.org.br/2011/


**Chris Nandor**
- http://use.perl.org/ -- no longer exist?
Suggestion: https://web.archive.org/web/20180213073300/http://use.perl.org/use.perl.org/


**Chris Prather**
- http://orlando.pm.org/ -- no longer an actual site.
Suggestion: link to https://www.pm.org/groups/592.html, at least it has a contact email (not Chris' though)
- http://www.perloasis.info/ -- "Service Unavailable" and looks like was used by spammers for the last few years
Suggestion: link to the latest WBM record: https://web.archive.org/web/20181121012657/http://www.perloasis.info/tbpw2014/
- http://www.yapcna.org/yn2015/ -- looks like a typo in year
Suggestion: -> http://www.yapcna.org/yn2014/


**David H. Adler**
- http://ny.pm.org/ -- same as for Adam Turoff
Suggestion: replace link to the meetup URL


**Dr. Tim Maher**
- http://ny.pm.org/ -- same as above

**Comment by szabgab** [comment]
Really nice detective work! Thank you!

IMHO the fact that some *.pm.org site now shows something else as in the case of http://ny.pm.org/ should be reported to the admins of https://pm.org/ (link to their github repo at the bottom of the page). Same if the url resolves. but there is no site behind it. e.g. http://orlando.pm.org/)  Those DNS configurations should be probably either removed or mapped to some page explaining that the specific PM groups are closed. Many years ago I went over all the pm sites, reported all the inactive ones and even got rid of them. If you have time it might be worth doing that again. (The  file `perl_mongers.xml` contains status of each one though I guess the DNS is manages separately.)

As for us, linking to the WBM where possible sound like a good idea, I think I'd include in the anchor text the original URL e.g. 
[Orlando Perl Mongers that used to be orlando.pm.org](https://www.pm.org/groups/592.html) for Chris Prather.

With ny.pm.org I'd probably include a link to both the WBM and the Meetup group. Actually as this one appears in several places, maybe add a page about it to our site and then link there. That way you don't need to repeat the explanation.

use.perl.org was shut down ages ago.

Please send PRs in small batched (e.g. all the ny.pm.org fixes can be in one batch) that way it will be easier to check them and also people later trying to understand what happened will have easier time.

Feel free to amend the text of each person with clarifications about the links.

**Comment by OpossumPetya** [comment]
ok, thanks! I'll work on this.

as for NY. pm, the pm org already links to their meetup.com page, and they seems to be using it (previous meet up was in May 2023), so I'd say is pretty save to link to it

**Comment by OpossumPetya** [comment]
Here's the rest of my findings, before I work on fixes...


**Gabor Szabo**
- http://perl.org.il/YAPC/ -- 404 not found
Suggestion: http://perl.org.il/yapc.html


**Graham Barr**
- http://search.cpan.org/ -- now redirects to https://metacpan.org/
Suggestion: link directly to https://metacpan.org/ with explanation


**Jacinta Richardson**
- http://perltraining.com.au/ -- not accessible
Suggestion: link to the latest WBM record: https://web.archive.org/web/20220730151827/http://perltraining.com.au/


**Jim Keenan**
- http://ny.pm.org/ -- same as above (meetup link)


**Karen Pauley**
- http://news.perlfoundation.org/2016/11/tpf-president-change.html -- redirects to newer URL structure
Suggestion: update to https://news.perlfoundation.org/post/tpf_president_change


**Kurt Demaagd**
- http://news.perlfoundation.org/2017/08/kurt-demaagd-stepping-down-fro.html -- redirects to newer URL structure
Suggestion: update to https://news.perlfoundation.org/post/kurt_demaagd_stepping_down_fro


**Leo Lapworth**
- http://www.perlnews.org/ -- redirects to perl.org
Suggestion: link to the latest WBM record: https://web.archive.org/web/20170411032641/http://perlnews.org/


**Nat Torkington**
- http://www.tpj.com/ -- redirects to a different website now
Suggestion: link to the latest WBM record: https://web.archive.org/web/20060412201354/http://www.tpj.com/


-----


**Randal Schwartz**
- http://www.stonehenge.com/merlyn -- without trailing slash redirects to http://127.0.0.1:8081/merlyn/
http://www.stonehenge.com/merlyn/
Suggestion: add trailing slash


**Renee Bäcker**
- http://yapcna.org/ -- currently redirects to https://tprc.us/tprc-2024-las/ , YAPC is The Perl and Raku Conference sine 2020. 
Suggestion: link "YAPC::NA" to https://tprc.us/, and "2012" to youtube video playlist from that conf: maybe add link https://www.youtube.com/playlist?list=PLE3F888A650339DDF


**Rob Masic**
- http://cluj.pm/ -- site no longer exist (since 2021?)
Suggestion: link to the latest WBM record: https://web.archive.org/web/20211202080119/https://cluj.pm/
- http://www.builtinperl.com/ - 403 Forbidden (down for a long time)
Suggestion: link to the latest WBM record: https://web.archive.org/web/20210518211152/http://www.builtinperl.com/


**Steffen Müller**
- https://blog.booking.com/author/steffen-muller.html -- 404 Not Found . the blog is still around, looks like posts are moved to medium.com, and Steffen's posts are still there (ex: https://medium.com/booking-com-development/more-optimizations-in-perl-5-20-to-be-d328d148d4c1), but old posts only mention authors inside text, and can't be filtered by those author.
Suggestion: link to their whole blog https://blog.booking.com/
- http://news.perlfoundation.org/2015/08/bookingcom-donate-60000-to-per-1.html -- redirects to newer URL structure
Suggestion: update to https://news.perlfoundation.org/post/bookingcom_donate_60000_to_per_1
- https://www.perlfoundation.org/perl_5_core_maintenance_fund -- Page Not Found
Suggestion: https://www.perlfoundation.org/perl-core-development-fund.html


**Thiago Rondon**
- http://sao-paulo.pm.org/equinocio/2013/mar/ - the link on "Equinócio" leads to a page that looks like a "not found" page
Suggestion: link to their Publications page - https://sao-paulo.pm.org/pub , it's not advent calendar, but a list of nice Perl technical posts

**Comment by abh** [comment]
@OpossumPetya Thank you for this!

I fixed ny.pm.org (when various caches update) to go to an appropriate pm.org page. Removing the link to my employer from more than 20 years ago makes a lot of sense. :-D

**Comment by szabgab** [comment]
I'd suggest notifying the owners of the target sites where it seems like an error on their end would be a better first step. e.g @RandalSchwartz about the the issue with the slash on his site.

I am also trying to fix the YAPC page on the perl.org.il site.

**Comment by OpossumPetya** [comment]
@abh aswesome! yep, redirect works.

@szabgab yep, i made a note to do it. also, plz bear with me as I'm trying to figure out some git stuff

**Comment by szabgab** [comment]
Sure. In the meantime I fixed the issue on the perl.org.il site

**Comment by OpossumPetya** [comment]
> As for us, linking to the WBM where possible sound like a good idea, I think I'd include in the anchor text the original URL e.g. [Orlando Perl Mongers that used to be orlando.pm.org](https://www.pm.org/groups/592.html) for Chris Prather.

I think instead of modifying the URL text, I will add a `class` to each web archive link, and later I'll style it with CSS a certain way (maybe adding a small SVG icon with text "web archive" or some archive icon) to indicate it is a web archive link.
